name: Deploy Vue

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm install

      - name: Build Vue App
        run: npm run build

      - name: Delete old dist folder on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT || '22' }}
          script: |
            rm -rf /home/${{ secrets.USERNAME }}/public_html/repositories/sawa-front.test/dist
            mkdir -p /home/${{ secrets.USERNAME }}/public_html/repositories/sawa-front.test/dist
            echo "✅ Old dist deleted and recreated"

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Upload new dist folder via rsync
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          rsync -avz \
          -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.PORT || '22' }}" \
          dist/ \
          ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/public_html/repositories/sawa-front.test/dist/
